### ISSUE TITLE
问题1

### ISSUE THREAD

**Issue by iou1992** [he010103/CFWCR#3]
请问 imagenet-vgg-m-2048-cut.mat在哪里下载？

**Comment by he010103** [comment]
wget http://www.vlfeat.org/matconvnet/models/imagenet-vgg-m-2048.mat. 
mv  imagenet-vgg-m-2048.mat imagenet-vgg-m-2048-cut.mat

**Comment by iou1992** [comment]
I can download the  imagenet-vgg-m-2048.mat from the matconvnet/model , but  I don't know where to find the imagenet-vgg-m-2048-cut.mat  file ?   what does the 'mv'  means ?   it's move?

**Comment by he010103** [comment]
change the name of the models.

**Comment by iou1992** [comment]
run demo_CFWCF.m    the result shown below the picture.
![result](https://user-images.githubusercontent.com/33022344/32986687-76474b60-cd12-11e7-9f16-d92307daedfb.gif)

**Comment by iou1992** [comment]
is ~/bash_profile in the readme.md a file?

**Comment by he010103** [comment]
@iou1992  please complie the matconvnet corectly http://www.vlfeat.org/matconvnet/install/!

**Comment by iou1992** [comment]
thank you very much.
run mex -setup  vl_compilenn  No problem appears.
but run demo_CFWCF.m the result shown below the picture.
![result2](https://user-images.githubusercontent.com/33022344/32991904-2f6d3944-cd7f-11e7-9ddb-12d6661e194e.GIF)

**Comment by he010103** [comment]
@iou1992  You need to compile in gpu option

**Comment by iou1992** [comment]
i choose to complie in cpu option . all the problem has solved. and the result did not show the process of tracking.thank you.

**Comment by iou1992** [comment]
the result did not show the process of tracking.
