### ISSUE TITLE
where the weighted sun operation in the code is?

### ISSUE THREAD

**Issue by iou1992** [he010103/CFWCR#4]
hello.
i had read the code.but i cannot find eq.4 and eq.5
![inkedr](https://user-images.githubusercontent.com/33022344/33365317-d186e20c-d522-11e7-976b-de9af6584792.gif)
can you tell me where eq.4 and eq.5 are in the code.
thanks in advance.

**Comment by he010103** [comment]
Set the parameter in the [https://github.com/he010103/CFWCR/blob/master/vot2017_trax/CFWCR_VOT.m](url)	

> params.weights = [1, 2];               	                % The weights factor
	params.weights_type    = 'sigmoid'; 		% type: constant, sigmoid
	params.divide_denominator = 100;
	params.initial = 1;
	params.factor = 0;

**Comment by iou1992** [comment]
thank you very much.
